-- Horoteca Supabase schema baseline — verified catalog 2026-08-26
-- Intended only for a new, empty, compatible Supabase project. Contains no operational rows or sequence values.
-- Do not run against the production project.

create table public.watches (
  "id" bigint generated by default as identity not null,
  "brand" text,
  "model" text,
  "reference_number" text,
  "movement_type" text,
  "case_material" text,
  "dial_color" text,
  "strap_material" text,
  "purchase_date" date,
  "purchase_price" numeric,
  "notes" text,
  "image_uri" text,
  "qr_code" text,
  "user_id" uuid not null default auth.uid(),
  "horoteca_code" text,
  "order_number" text,
  "order_item_number" integer,
  "marketplace" text,
  "marketplace_item_id" text,
  "seller_name" text,
  "purchase_currency" text,
  "purchase_amount_original" numeric(14,2),
  "purchase_total_brl" numeric(14,2),
  "payment_method" text,
  "estimated_value" numeric(14,2),
  "estimated_value_date" date,
  "manufacture_year" integer,
  "movement_caliber" text,
  "condition" text,
  "brand_id" bigint,
  "watch_model_id" bigint,
  "movement_caliber_id" bigint,
  "serial_number" text,
  "case_code" text,
  "dial_code" text,
  "movement_description" text,
  "jewels" smallint,
  "complications" text[],
  "manufacture_country" text,
  "manufacture_year_is_estimated" boolean,
  "production_period_start_year" smallint,
  "production_period_end_year" smallint,
  "diameter_mm" numeric(6,2),
  "case_thickness_mm" numeric(6,2),
  "lug_to_lug_mm" numeric(6,2),
  "lug_width_mm" numeric(6,2),
  "case_finish" text,
  "case_color" text,
  "case_shape" text,
  "dial_description" text,
  "dial_inscriptions" text,
  "indices_description" text,
  "hands_description" text,
  "crystal_material" text,
  "crystal_condition" text,
  "crown_description" text,
  "caseback_description" text,
  "caseback_inscriptions" text,
  "strap_description" text,
  "clasp_type" text,
  "strap_originality" text,
  "dial_originality" text,
  "component_originality" text,
  "function_status" text,
  "accuracy_seconds_per_day" numeric(8,2),
  "accuracy_notes" text,
  "known_defects" text,
  "water_resistance" text,
  "source_document_url" text,
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "watch_type" text,
  "display_type" text,
  "intended_audience" text,
  "bezel_type" text,
  "bezel_material" text,
  "bezel_color" text,
  "strap_color" text,
  "has_original_box" boolean,
  "has_original_papers" boolean,
  "included_accessories" text[],
  "is_customized" boolean,
  "customization_description" text,
  "features" text[]
);

create table public.maintenance_logs (
  "id" bigint generated by default as identity not null,
  "watch_id" bigint,
  "service_date" date,
  "description" text not null,
  "service_provider" text,
  "cost" numeric,
  "next_service_due" text,
  "user_id" uuid not null default auth.uid(),
  "event_type" text not null default 'manutencao'::text,
  "expense_category" text,
  "currency" text not null default 'BRL'::text,
  "amount_original" numeric(14,2),
  "amount_brl" numeric(14,2),
  "event_date" date,
  "notes" text,
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now()
);

create table public.brands (
  "id" bigint generated by default as identity not null,
  "user_id" uuid not null default auth.uid(),
  "name" text not null,
  "country" text,
  "founded_year" integer,
  "founder" text,
  "history" text,
  "milestones" text,
  "technologies" text,
  "curiosities" text,
  "logo_path" text,
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now()
);

create table public.watch_photos (
  "id" bigint generated by default as identity not null,
  "watch_id" bigint,
  "user_id" uuid not null default auth.uid(),
  "storage_path" text not null,
  "caption" text,
  "is_cover" boolean not null default false,
  "sort_order" integer not null default 0,
  "created_at" timestamptz not null default now(),
  "acquisition_id" bigint,
  "photo_type" text,
  "source_type" text,
  "source_url" text,
  "evidence_classification" text,
  "notes" text,
  "updated_at" timestamptz not null default now()
);

create table public.watch_models (
  "id" bigint generated by default as identity not null,
  "user_id" uuid not null default auth.uid(),
  "brand_id" bigint,
  "model_name" text not null,
  "line_name" text,
  "reference_family" text,
  "launch_year" smallint,
  "production_start_year" smallint,
  "production_end_year" smallint,
  "designer" text,
  "creation_context" text,
  "history" text,
  "notable_features" text,
  "historical_importance" text,
  "history_sources" jsonb,
  "reviewed_at" date,
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now()
);

create table public.movement_calibers (
  "id" bigint generated by default as identity not null,
  "user_id" uuid not null default auth.uid(),
  "manufacturer" text,
  "caliber_code" text not null,
  "movement_type" text,
  "jewels" smallint,
  "complications" text[],
  "production_start_year" smallint,
  "production_end_year" smallint,
  "technical_description" text,
  "history" text,
  "historical_importance" text,
  "history_sources" jsonb,
  "reviewed_at" date,
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "frequency_vph" integer,
  "power_reserve_hours" numeric(6,2),
  "movement_diameter_mm" numeric(6,2),
  "movement_thickness_mm" numeric(6,2),
  "has_manual_winding" boolean,
  "has_hacking_seconds" boolean,
  "quickset_features" text[],
  "shock_protection" text,
  "escapement_type" text,
  "winding_description" text
);

create table public.acquisitions (
  "id" bigint generated by default as identity not null,
  "user_id" uuid not null default auth.uid(),
  "marketplace" text,
  "seller_name" text,
  "order_number" text,
  "purchase_date" date,
  "purchase_payment_date" date,
  "taxes_payment_date" date,
  "shipped_date" date,
  "received_date" date,
  "payment_method" text,
  "carrier" text,
  "tracking_number" text,
  "source_document_url" text,
  "notes" text,
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "estimated_delivery_date" date,
  "source_document_name" text
);

create table public.acquisition_items (
  "id" bigint generated by default as identity not null,
  "user_id" uuid not null default auth.uid(),
  "acquisition_id" bigint not null,
  "watch_id" bigint not null,
  "item_sequence" integer not null,
  "marketplace_item_id" text,
  "visual_position" text,
  "individual_price_original" numeric(14,2),
  "currency" text,
  "individual_price_brl" numeric(14,2),
  "allocation_basis" text,
  "notes" text,
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "listing_title" text,
  "listing_url" text,
  "listing_category" text,
  "seller_condition_label" text,
  "seller_condition_description" text,
  "listing_quantity" integer,
  "listing_language" text,
  "listing_specifics" jsonb not null default '{}'::jsonb,
  "listing_captured_at" date
);

create table public.expenses (
  "id" bigint generated by default as identity not null,
  "user_id" uuid not null default auth.uid(),
  "acquisition_id" bigint,
  "watch_id" bigint,
  "category" text not null,
  "description" text,
  "expense_date" date,
  "currency" text not null,
  "amount_original" numeric(14,2) not null,
  "exchange_rate" numeric(18,6),
  "amount_brl" numeric(14,2),
  "is_shared" boolean not null default false,
  "allocation_method" text,
  "source_reference" text,
  "notes" text,
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now()
);

create table public.expense_allocations (
  "id" bigint generated by default as identity not null,
  "user_id" uuid not null default auth.uid(),
  "expense_id" bigint not null,
  "watch_id" bigint not null,
  "amount_original_allocated" numeric(14,2),
  "amount_brl_allocated" numeric(14,2) not null,
  "rounding_adjustment_brl" numeric(14,2) not null default 0,
  "allocation_basis" text,
  "created_at" timestamptz not null default now()
);

create table public.watch_events (
  "id" bigint generated by default as identity not null,
  "user_id" uuid not null default auth.uid(),
  "watch_id" bigint,
  "acquisition_id" bigint,
  "event_type" text not null,
  "event_date" date not null,
  "description" text not null,
  "provider" text,
  "expense_id" bigint,
  "parts_replaced" text,
  "function_before" text,
  "function_after" text,
  "next_service_due" date,
  "notes" text,
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now()
);

create table public.watch_sources (
  "id" bigint generated by default as identity not null,
  "user_id" uuid not null default auth.uid(),
  "watch_id" bigint,
  "acquisition_id" bigint,
  "source_type" text not null,
  "source_name" text,
  "source_url" text,
  "evidence_classification" text not null,
  "confidence_percent" smallint,
  "excerpt" text,
  "notes" text,
  "accessed_at" date,
  "created_at" timestamptz not null default now()
);

create table public.watch_photo_links (
  "id" bigint generated by default as identity not null,
  "user_id" uuid not null default auth.uid(),
  "photo_id" bigint not null,
  "watch_id" bigint not null,
  "visual_position" text,
  "notes" text,
  "created_at" timestamptz not null default now()
);

create table public.watch_claims (
  "id" bigint generated by default as identity not null,
  "user_id" uuid not null default auth.uid(),
  "watch_id" bigint not null,
  "source_id" bigint,
  "field_name" text not null,
  "asserted_value" text not null,
  "normalized_value" text,
  "evidence_classification" text not null,
  "verification_status" text not null default 'pending'::text,
  "confidence_percent" smallint,
  "claim_context" text,
  "notes" text,
  "reviewed_at" timestamptz,
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now()
);

-- Primary keys, foreign keys, checks and unique constraints.
alter table public.acquisition_items add constraint "acquisition_items_pkey" PRIMARY KEY (id);
alter table public.acquisitions add constraint "acquisitions_pkey" PRIMARY KEY (id);
alter table public.brands add constraint "brands_pkey" PRIMARY KEY (id);
alter table public.expense_allocations add constraint "expense_allocations_pkey" PRIMARY KEY (id);
alter table public.expenses add constraint "expenses_pkey" PRIMARY KEY (id);
alter table public.maintenance_logs add constraint "maintenance_logs_pkey" PRIMARY KEY (id);
alter table public.movement_calibers add constraint "movement_calibers_pkey" PRIMARY KEY (id);
alter table public.watch_claims add constraint "watch_claims_pkey" PRIMARY KEY (id);
alter table public.watch_events add constraint "watch_events_pkey" PRIMARY KEY (id);
alter table public.watch_models add constraint "watch_models_pkey" PRIMARY KEY (id);
alter table public.watch_photo_links add constraint "watch_photo_links_pkey" PRIMARY KEY (id);
alter table public.watch_photos add constraint "watch_photos_pkey" PRIMARY KEY (id);
alter table public.watch_sources add constraint "watch_sources_pkey" PRIMARY KEY (id);
alter table public.watches add constraint "watches_pkey" PRIMARY KEY (id);
alter table public.acquisition_items add constraint "acquisition_items_listing_quantity_check" CHECK (listing_quantity IS NULL OR listing_quantity > 0);
alter table public.acquisition_items add constraint "acquisition_items_sequence_check" CHECK (item_sequence > 0);
alter table public.acquisition_items add constraint "acquisition_items_acquisition_id_fkey" FOREIGN KEY (acquisition_id) REFERENCES public.acquisitions(id) ON DELETE CASCADE;
alter table public.acquisition_items add constraint "acquisition_items_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.acquisition_items add constraint "acquisition_items_watch_id_fkey" FOREIGN KEY (watch_id) REFERENCES public.watches(id) ON DELETE CASCADE;
alter table public.acquisition_items add constraint "acquisition_items_acquisition_sequence_key" UNIQUE (acquisition_id, item_sequence);
alter table public.acquisition_items add constraint "acquisition_items_watch_key" UNIQUE (watch_id);
alter table public.acquisitions add constraint "acquisitions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.brands add constraint "brands_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id);
alter table public.brands add constraint "brands_user_id_name_key" UNIQUE (user_id, name);
alter table public.expense_allocations add constraint "expense_allocations_amounts_check" CHECK ((amount_original_allocated IS NULL OR amount_original_allocated >= 0::numeric) AND amount_brl_allocated >= 0::numeric);
alter table public.expense_allocations add constraint "expense_allocations_expense_id_fkey" FOREIGN KEY (expense_id) REFERENCES public.expenses(id) ON DELETE CASCADE;
alter table public.expense_allocations add constraint "expense_allocations_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.expense_allocations add constraint "expense_allocations_watch_id_fkey" FOREIGN KEY (watch_id) REFERENCES public.watches(id) ON DELETE CASCADE;
alter table public.expense_allocations add constraint "expense_allocations_expense_watch_key" UNIQUE (expense_id, watch_id);
alter table public.expenses add constraint "expenses_amounts_check" CHECK (amount_original >= 0::numeric AND (amount_brl IS NULL OR amount_brl >= 0::numeric) AND (exchange_rate IS NULL OR exchange_rate > 0::numeric));
alter table public.expenses add constraint "expenses_category_check" CHECK (category = ANY (ARRAY['product'::text, 'freight'::text, 'tax'::text, 'fee'::text, 'carrier'::text, 'maintenance'::text, 'parts'::text, 'strap'::text, 'other'::text]));
alter table public.expenses add constraint "expenses_owner_check" CHECK (acquisition_id IS NOT NULL OR watch_id IS NOT NULL);
alter table public.expenses add constraint "expenses_acquisition_id_fkey" FOREIGN KEY (acquisition_id) REFERENCES public.acquisitions(id) ON DELETE CASCADE;
alter table public.expenses add constraint "expenses_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.expenses add constraint "expenses_watch_id_fkey" FOREIGN KEY (watch_id) REFERENCES public.watches(id) ON DELETE CASCADE;
alter table public.maintenance_logs add constraint "maintenance_logs_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id);
alter table public.maintenance_logs add constraint "maintenance_logs_watch_id_fkey" FOREIGN KEY (watch_id) REFERENCES public.watches(id) ON DELETE CASCADE;
alter table public.movement_calibers add constraint "movement_calibers_jewels_check" CHECK (jewels IS NULL OR jewels >= 0 AND jewels <= 200);
alter table public.movement_calibers add constraint "movement_calibers_specs_check" CHECK ((frequency_vph IS NULL OR frequency_vph > 0) AND (power_reserve_hours IS NULL OR power_reserve_hours > 0::numeric) AND (movement_diameter_mm IS NULL OR movement_diameter_mm > 0::numeric) AND (movement_thickness_mm IS NULL OR movement_thickness_mm > 0::numeric));
alter table public.movement_calibers add constraint "movement_calibers_years_check" CHECK (production_start_year IS NULL OR production_end_year IS NULL OR production_start_year <= production_end_year);
alter table public.movement_calibers add constraint "movement_calibers_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.watch_claims add constraint "watch_claims_asserted_value_check" CHECK (btrim(asserted_value) <> ''::text);
alter table public.watch_claims add constraint "watch_claims_classification_check" CHECK (evidence_classification = ANY (ARRAY['document_confirmed'::text, 'seller_statement'::text, 'visual_observation'::text, 'researched'::text, 'estimated'::text, 'missing'::text, 'inconsistent'::text]));
alter table public.watch_claims add constraint "watch_claims_confidence_check" CHECK (confidence_percent IS NULL OR confidence_percent >= 0 AND confidence_percent <= 100);
alter table public.watch_claims add constraint "watch_claims_field_name_check" CHECK (btrim(field_name) <> ''::text);
alter table public.watch_claims add constraint "watch_claims_status_check" CHECK (verification_status = ANY (ARRAY['pending'::text, 'accepted'::text, 'rejected'::text, 'superseded'::text]));
alter table public.watch_claims add constraint "watch_claims_source_id_fkey" FOREIGN KEY (source_id) REFERENCES public.watch_sources(id) ON DELETE SET NULL;
alter table public.watch_claims add constraint "watch_claims_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.watch_claims add constraint "watch_claims_watch_id_fkey" FOREIGN KEY (watch_id) REFERENCES public.watches(id) ON DELETE CASCADE;
alter table public.watch_events add constraint "watch_events_owner_check" CHECK (watch_id IS NOT NULL OR acquisition_id IS NOT NULL);
alter table public.watch_events add constraint "watch_events_type_check" CHECK (event_type = ANY (ARRAY['purchase'::text, 'payment'::text, 'shipment'::text, 'customs'::text, 'receipt'::text, 'inspection'::text, 'maintenance'::text, 'parts_replacement'::text, 'valuation'::text, 'sale'::text, 'retirement'::text, 'other'::text]));
alter table public.watch_events add constraint "watch_events_acquisition_id_fkey" FOREIGN KEY (acquisition_id) REFERENCES public.acquisitions(id) ON DELETE CASCADE;
alter table public.watch_events add constraint "watch_events_expense_id_fkey" FOREIGN KEY (expense_id) REFERENCES public.expenses(id) ON DELETE SET NULL;
alter table public.watch_events add constraint "watch_events_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.watch_events add constraint "watch_events_watch_id_fkey" FOREIGN KEY (watch_id) REFERENCES public.watches(id) ON DELETE CASCADE;
alter table public.watch_models add constraint "watch_models_years_check" CHECK (production_start_year IS NULL OR production_end_year IS NULL OR production_start_year <= production_end_year);
alter table public.watch_models add constraint "watch_models_brand_id_fkey" FOREIGN KEY (brand_id) REFERENCES public.brands(id) ON DELETE SET NULL;
alter table public.watch_models add constraint "watch_models_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.watch_photo_links add constraint "watch_photo_links_photo_id_fkey" FOREIGN KEY (photo_id) REFERENCES public.watch_photos(id) ON DELETE CASCADE;
alter table public.watch_photo_links add constraint "watch_photo_links_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.watch_photo_links add constraint "watch_photo_links_watch_id_fkey" FOREIGN KEY (watch_id) REFERENCES public.watches(id) ON DELETE CASCADE;
alter table public.watch_photo_links add constraint "watch_photo_links_photo_watch_key" UNIQUE (photo_id, watch_id);
alter table public.watch_photos add constraint "watch_photos_classification_check" CHECK (evidence_classification IS NULL OR (evidence_classification = ANY (ARRAY['document_confirmed'::text, 'seller_statement'::text, 'visual_observation'::text, 'researched'::text, 'estimated'::text, 'missing'::text, 'inconsistent'::text])));
alter table public.watch_photos add constraint "watch_photos_owner_check" CHECK (watch_id IS NOT NULL OR acquisition_id IS NOT NULL);
alter table public.watch_photos add constraint "watch_photos_acquisition_id_fkey" FOREIGN KEY (acquisition_id) REFERENCES public.acquisitions(id) ON DELETE CASCADE;
alter table public.watch_photos add constraint "watch_photos_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id);
alter table public.watch_photos add constraint "watch_photos_watch_id_fkey" FOREIGN KEY (watch_id) REFERENCES public.watches(id) ON DELETE CASCADE;
alter table public.watch_photos add constraint "watch_photos_user_id_storage_path_key" UNIQUE (user_id, storage_path);
alter table public.watch_sources add constraint "watch_sources_classification_check" CHECK (evidence_classification = ANY (ARRAY['document_confirmed'::text, 'seller_statement'::text, 'visual_observation'::text, 'researched'::text, 'estimated'::text, 'missing'::text, 'inconsistent'::text]));
alter table public.watch_sources add constraint "watch_sources_confidence_check" CHECK (confidence_percent IS NULL OR confidence_percent >= 0 AND confidence_percent <= 100);
alter table public.watch_sources add constraint "watch_sources_owner_check" CHECK (watch_id IS NOT NULL OR acquisition_id IS NOT NULL);
alter table public.watch_sources add constraint "watch_sources_acquisition_id_fkey" FOREIGN KEY (acquisition_id) REFERENCES public.acquisitions(id) ON DELETE CASCADE;
alter table public.watch_sources add constraint "watch_sources_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.watch_sources add constraint "watch_sources_watch_id_fkey" FOREIGN KEY (watch_id) REFERENCES public.watches(id) ON DELETE CASCADE;
alter table public.watches add constraint "watches_dimensions_check" CHECK ((diameter_mm IS NULL OR diameter_mm > 0::numeric) AND (case_thickness_mm IS NULL OR case_thickness_mm > 0::numeric) AND (lug_to_lug_mm IS NULL OR lug_to_lug_mm > 0::numeric) AND (lug_width_mm IS NULL OR lug_width_mm > 0::numeric));
alter table public.watches add constraint "watches_jewels_check" CHECK (jewels IS NULL OR jewels >= 0 AND jewels <= 200);
alter table public.watches add constraint "watches_year_period_check" CHECK (production_period_start_year IS NULL OR production_period_end_year IS NULL OR production_period_start_year <= production_period_end_year);
alter table public.watches add constraint "watches_brand_id_fkey" FOREIGN KEY (brand_id) REFERENCES public.brands(id) ON DELETE SET NULL;
alter table public.watches add constraint "watches_movement_caliber_id_fkey" FOREIGN KEY (movement_caliber_id) REFERENCES public.movement_calibers(id) ON DELETE SET NULL;
alter table public.watches add constraint "watches_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE RESTRICT;
alter table public.watches add constraint "watches_watch_model_id_fkey" FOREIGN KEY (watch_model_id) REFERENCES public.watch_models(id) ON DELETE SET NULL;

-- Non-constraint indexes (constraint-backed indexes are created by constraints above).
CREATE INDEX acquisition_items_acquisition_id_idx ON public.acquisition_items USING btree (acquisition_id);
CREATE INDEX acquisition_items_listing_specifics_gin_idx ON public.acquisition_items USING gin (listing_specifics);
CREATE INDEX acquisition_items_user_id_idx ON public.acquisition_items USING btree (user_id);
CREATE INDEX acquisitions_user_id_idx ON public.acquisitions USING btree (user_id);
CREATE UNIQUE INDEX acquisitions_user_order_uidx ON public.acquisitions USING btree (user_id, lower(COALESCE(marketplace, ''::text)), order_number) WHERE order_number IS NOT NULL;
CREATE INDEX expense_allocations_expense_id_idx ON public.expense_allocations USING btree (expense_id);
CREATE INDEX expense_allocations_user_id_idx ON public.expense_allocations USING btree (user_id);
CREATE INDEX expense_allocations_watch_id_idx ON public.expense_allocations USING btree (watch_id);
CREATE INDEX expenses_acquisition_id_idx ON public.expenses USING btree (acquisition_id);
CREATE INDEX expenses_user_id_idx ON public.expenses USING btree (user_id);
CREATE INDEX expenses_watch_id_idx ON public.expenses USING btree (watch_id);
CREATE INDEX maintenance_logs_user_id_idx ON public.maintenance_logs USING btree (user_id);
CREATE INDEX maintenance_logs_watch_id_idx ON public.maintenance_logs USING btree (watch_id);
CREATE INDEX movement_calibers_user_id_idx ON public.movement_calibers USING btree (user_id);
CREATE UNIQUE INDEX movement_calibers_user_identity_uidx ON public.movement_calibers USING btree (user_id, lower(COALESCE(manufacturer, ''::text)), lower(caliber_code));
CREATE INDEX watch_claims_review_idx ON public.watch_claims USING btree (watch_id, verification_status, field_name);
CREATE INDEX watch_claims_source_id_idx ON public.watch_claims USING btree (source_id);
CREATE INDEX watch_claims_user_id_idx ON public.watch_claims USING btree (user_id);
CREATE INDEX watch_claims_watch_id_idx ON public.watch_claims USING btree (watch_id);
CREATE INDEX watch_events_acquisition_id_idx ON public.watch_events USING btree (acquisition_id);
CREATE INDEX watch_events_expense_id_idx ON public.watch_events USING btree (expense_id);
CREATE INDEX watch_events_user_id_idx ON public.watch_events USING btree (user_id);
CREATE INDEX watch_events_watch_date_idx ON public.watch_events USING btree (watch_id, event_date DESC);
CREATE INDEX watch_models_brand_id_idx ON public.watch_models USING btree (brand_id);
CREATE INDEX watch_models_user_id_idx ON public.watch_models USING btree (user_id);
CREATE UNIQUE INDEX watch_models_user_identity_uidx ON public.watch_models USING btree (user_id, COALESCE(brand_id, 0::bigint), lower(model_name), lower(COALESCE(line_name, ''::text)), lower(COALESCE(reference_family, ''::text)));
CREATE INDEX watch_photo_links_photo_id_idx ON public.watch_photo_links USING btree (photo_id);
CREATE INDEX watch_photo_links_user_id_idx ON public.watch_photo_links USING btree (user_id);
CREATE INDEX watch_photo_links_watch_id_idx ON public.watch_photo_links USING btree (watch_id);
CREATE INDEX watch_photos_acquisition_id_idx ON public.watch_photos USING btree (acquisition_id);
CREATE INDEX watch_photos_watch_id_idx ON public.watch_photos USING btree (watch_id);
CREATE INDEX watch_sources_acquisition_id_idx ON public.watch_sources USING btree (acquisition_id);
CREATE INDEX watch_sources_user_id_idx ON public.watch_sources USING btree (user_id);
CREATE INDEX watch_sources_watch_id_idx ON public.watch_sources USING btree (watch_id);
CREATE INDEX watches_brand_id_idx ON public.watches USING btree (brand_id);
CREATE INDEX watches_movement_caliber_id_idx ON public.watches USING btree (movement_caliber_id);
CREATE UNIQUE INDEX watches_user_horoteca_code_uidx ON public.watches USING btree (user_id, horoteca_code) WHERE horoteca_code IS NOT NULL;
CREATE INDEX watches_user_id_idx ON public.watches USING btree (user_id);
CREATE UNIQUE INDEX watches_user_order_item_uidx ON public.watches USING btree (user_id, lower(COALESCE(marketplace, ''::text)), order_number, order_item_number) WHERE order_number IS NOT NULL AND order_item_number IS NOT NULL;
CREATE INDEX watches_watch_model_id_idx ON public.watches USING btree (watch_model_id);

-- Timestamp maintenance function and triggers.
CREATE OR REPLACE FUNCTION public.set_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
begin
  new.updated_at = now();
  return new;
end;
$function$;
revoke execute on function public.set_updated_at() from public, anon, authenticated, service_role;
grant execute on function public.set_updated_at() to service_role;
CREATE TRIGGER acquisition_items_set_updated_at BEFORE UPDATE ON public.acquisition_items FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER acquisitions_set_updated_at BEFORE UPDATE ON public.acquisitions FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER expenses_set_updated_at BEFORE UPDATE ON public.expenses FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER maintenance_logs_set_updated_at BEFORE UPDATE ON public.maintenance_logs FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER movement_calibers_set_updated_at BEFORE UPDATE ON public.movement_calibers FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER watch_claims_set_updated_at BEFORE UPDATE ON public.watch_claims FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER watch_events_set_updated_at BEFORE UPDATE ON public.watch_events FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER watch_models_set_updated_at BEFORE UPDATE ON public.watch_models FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER watches_set_updated_at BEFORE UPDATE ON public.watches FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Row-level security and operation-specific policies.
alter table public.watches enable row level security;
alter table public.maintenance_logs enable row level security;
alter table public.brands enable row level security;
alter table public.watch_photos enable row level security;
alter table public.watch_models enable row level security;
alter table public.movement_calibers enable row level security;
alter table public.acquisitions enable row level security;
alter table public.acquisition_items enable row level security;
alter table public.expenses enable row level security;
alter table public.expense_allocations enable row level security;
alter table public.watch_events enable row level security;
alter table public.watch_sources enable row level security;
alter table public.watch_photo_links enable row level security;
alter table public.watch_claims enable row level security;
create policy "owner_delete" on public.acquisition_items as permissive for delete to authenticated
  using ((( SELECT auth.uid() AS uid) = user_id))
;
create policy "owner_insert" on public.acquisition_items as permissive for insert to authenticated
  with check (((( SELECT auth.uid() AS uid) = user_id) AND (EXISTS ( SELECT 1
   FROM acquisitions acquisition
  WHERE ((acquisition.id = acquisition_items.acquisition_id) AND (acquisition.user_id = ( SELECT auth.uid() AS uid))))) AND (EXISTS ( SELECT 1
   FROM watches watch
  WHERE ((watch.id = acquisition_items.watch_id) AND (watch.user_id = ( SELECT auth.uid() AS uid)))))))
;
create policy "owner_select" on public.acquisition_items as permissive for select to authenticated
  using ((( SELECT auth.uid() AS uid) = user_id))
;
create policy "owner_update" on public.acquisition_items as permissive for update to authenticated
  using ((( SELECT auth.uid() AS uid) = user_id))
  with check (((( SELECT auth.uid() AS uid) = user_id) AND (EXISTS ( SELECT 1
   FROM acquisitions acquisition
  WHERE ((acquisition.id = acquisition_items.acquisition_id) AND (acquisition.user_id = ( SELECT auth.uid() AS uid))))) AND (EXISTS ( SELECT 1
   FROM watches watch
  WHERE ((watch.id = acquisition_items.watch_id) AND (watch.user_id = ( SELECT auth.uid() AS uid)))))))
;
create policy "owner_delete" on public.acquisitions as permissive for delete to authenticated
  using ((( SELECT auth.uid() AS uid) = user_id))
;
create policy "owner_insert" on public.acquisitions as permissive for insert to authenticated
  with check ((( SELECT auth.uid() AS uid) = user_id))
;
create policy "owner_select" on public.acquisitions as permissive for select to authenticated
  using ((( SELECT auth.uid() AS uid) = user_id))
;
create policy "owner_update" on public.acquisitions as permissive for update to authenticated
  using ((( SELECT auth.uid() AS uid) = user_id))
  with check ((( SELECT auth.uid() AS uid) = user_id))
;
create policy "owner_delete_brands" on public.brands as permissive for delete to authenticated
  using ((( SELECT auth.uid() AS uid) = user_id))
;
create policy "owner_insert_brands" on public.brands as permissive for insert to authenticated
  with check ((( SELECT auth.uid() AS uid) = user_id))
;
create policy "owner_select_brands" on public.brands as permissive for select to authenticated
  using ((( SELECT auth.uid() AS uid) = user_id))
;
create policy "owner_update_brands" on public.brands as permissive for update to authenticated
  using ((( SELECT auth.uid() AS uid) = user_id))
  with check ((( SELECT auth.uid() AS uid) = user_id))
;
create policy "owner_delete" on public.expense_allocations as permissive for delete to authenticated
  using ((( SELECT auth.uid() AS uid) = user_id))
;
create policy "owner_insert" on public.expense_allocations as permissive for insert to authenticated
  with check (((( SELECT auth.uid() AS uid) = user_id) AND (EXISTS ( SELECT 1
   FROM expenses expense
  WHERE ((expense.id = expense_allocations.expense_id) AND (expense.user_id = ( SELECT auth.uid() AS uid))))) AND (EXISTS ( SELECT 1
   FROM watches watch
  WHERE ((watch.id = expense_allocations.watch_id) AND (watch.user_id = ( SELECT auth.uid() AS uid)))))))
;
create policy "owner_select" on public.expense_allocations as permissive for select to authenticated
  using ((( SELECT auth.uid() AS uid) = user_id))
;
create policy "owner_update" on public.expense_allocations as permissive for update to authenticated
  using ((( SELECT auth.uid() AS uid) = user_id))
  with check (((( SELECT auth.uid() AS uid) = user_id) AND (EXISTS ( SELECT 1
   FROM expenses expense
  WHERE ((expense.id = expense_allocations.expense_id) AND (expense.user_id = ( SELECT auth.uid() AS uid))))) AND (EXISTS ( SELECT 1
   FROM watches watch
  WHERE ((watch.id = expense_allocations.watch_id) AND (watch.user_id = ( SELECT auth.uid() AS uid)))))))
;
create policy "owner_delete" on public.expenses as permissive for delete to authenticated
  using ((( SELECT auth.uid() AS uid) = user_id))
;
create policy "owner_insert" on public.expenses as permissive for insert to authenticated
  with check (((( SELECT auth.uid() AS uid) = user_id) AND ((watch_id IS NULL) OR (EXISTS ( SELECT 1
   FROM watches watch
  WHERE ((watch.id = expenses.watch_id) AND (watch.user_id = ( SELECT auth.uid() AS uid)))))) AND ((acquisition_id IS NULL) OR (EXISTS ( SELECT 1
   FROM acquisitions acquisition
  WHERE ((acquisition.id = expenses.acquisition_id) AND (acquisition.user_id = ( SELECT auth.uid() AS uid))))))))
;
create policy "owner_select" on public.expenses as permissive for select to authenticated
  using ((( SELECT auth.uid() AS uid) = user_id))
;
create policy "owner_update" on public.expenses as permissive for update to authenticated
  using ((( SELECT auth.uid() AS uid) = user_id))
  with check (((( SELECT auth.uid() AS uid) = user_id) AND ((watch_id IS NULL) OR (EXISTS ( SELECT 1
   FROM watches watch
  WHERE ((watch.id = expenses.watch_id) AND (watch.user_id = ( SELECT auth.uid() AS uid)))))) AND ((acquisition_id IS NULL) OR (EXISTS ( SELECT 1
   FROM acquisitions acquisition
  WHERE ((acquisition.id = expenses.acquisition_id) AND (acquisition.user_id = ( SELECT auth.uid() AS uid))))))))
;
create policy "owner_delete_maintenance_logs" on public.maintenance_logs as permissive for delete to authenticated
  using ((( SELECT auth.uid() AS uid) = user_id))
;
create policy "owner_insert_maintenance_logs" on public.maintenance_logs as permissive for insert to authenticated
  with check (((( SELECT auth.uid() AS uid) = user_id) AND (EXISTS ( SELECT 1
   FROM watches w
  WHERE ((w.id = maintenance_logs.watch_id) AND (w.user_id = ( SELECT auth.uid() AS uid)))))))
;
create policy "owner_select_maintenance_logs" on public.maintenance_logs as permissive for select to authenticated
  using ((( SELECT auth.uid() AS uid) = user_id))
;
create policy "owner_update_maintenance_logs" on public.maintenance_logs as permissive for update to authenticated
  using ((( SELECT auth.uid() AS uid) = user_id))
  with check (((( SELECT auth.uid() AS uid) = user_id) AND (EXISTS ( SELECT 1
   FROM watches w
  WHERE ((w.id = maintenance_logs.watch_id) AND (w.user_id = ( SELECT auth.uid() AS uid)))))))
;
create policy "owner_delete" on public.movement_calibers as permissive for delete to authenticated
  using ((( SELECT auth.uid() AS uid) = user_id))
;
create policy "owner_insert" on public.movement_calibers as permissive for insert to authenticated
  with check ((( SELECT auth.uid() AS uid) = user_id))
;
create policy "owner_select" on public.movement_calibers as permissive for select to authenticated
  using ((( SELECT auth.uid() AS uid) = user_id))
;
create policy "owner_update" on public.movement_calibers as permissive for update to authenticated
  using ((( SELECT auth.uid() AS uid) = user_id))
  with check ((( SELECT auth.uid() AS uid) = user_id))
;
create policy "owner_delete" on public.watch_claims as permissive for delete to authenticated
  using ((( SELECT auth.uid() AS uid) = user_id))
;
create policy "owner_insert" on public.watch_claims as permissive for insert to authenticated
  with check (((( SELECT auth.uid() AS uid) = user_id) AND (EXISTS ( SELECT 1
   FROM watches watch
  WHERE ((watch.id = watch_claims.watch_id) AND (watch.user_id = ( SELECT auth.uid() AS uid))))) AND ((source_id IS NULL) OR (EXISTS ( SELECT 1
   FROM watch_sources source
  WHERE ((source.id = watch_claims.source_id) AND (source.user_id = ( SELECT auth.uid() AS uid))))))))
;
create policy "owner_select" on public.watch_claims as permissive for select to authenticated
  using ((( SELECT auth.uid() AS uid) = user_id))
;
create policy "owner_update" on public.watch_claims as permissive for update to authenticated
  using ((( SELECT auth.uid() AS uid) = user_id))
  with check (((( SELECT auth.uid() AS uid) = user_id) AND (EXISTS ( SELECT 1
   FROM watches watch
  WHERE ((watch.id = watch_claims.watch_id) AND (watch.user_id = ( SELECT auth.uid() AS uid))))) AND ((source_id IS NULL) OR (EXISTS ( SELECT 1
   FROM watch_sources source
  WHERE ((source.id = watch_claims.source_id) AND (source.user_id = ( SELECT auth.uid() AS uid))))))))
;
create policy "owner_delete" on public.watch_events as permissive for delete to authenticated
  using ((( SELECT auth.uid() AS uid) = user_id))
;
create policy "owner_insert" on public.watch_events as permissive for insert to authenticated
  with check (((( SELECT auth.uid() AS uid) = user_id) AND ((watch_id IS NULL) OR (EXISTS ( SELECT 1
   FROM watches watch
  WHERE ((watch.id = watch_events.watch_id) AND (watch.user_id = ( SELECT auth.uid() AS uid)))))) AND ((acquisition_id IS NULL) OR (EXISTS ( SELECT 1
   FROM acquisitions acquisition
  WHERE ((acquisition.id = watch_events.acquisition_id) AND (acquisition.user_id = ( SELECT auth.uid() AS uid)))))) AND ((expense_id IS NULL) OR (EXISTS ( SELECT 1
   FROM expenses expense
  WHERE ((expense.id = watch_events.expense_id) AND (expense.user_id = ( SELECT auth.uid() AS uid))))))))
;
create policy "owner_select" on public.watch_events as permissive for select to authenticated
  using ((( SELECT auth.uid() AS uid) = user_id))
;
create policy "owner_update" on public.watch_events as permissive for update to authenticated
  using ((( SELECT auth.uid() AS uid) = user_id))
  with check (((( SELECT auth.uid() AS uid) = user_id) AND ((watch_id IS NULL) OR (EXISTS ( SELECT 1
   FROM watches watch
  WHERE ((watch.id = watch_events.watch_id) AND (watch.user_id = ( SELECT auth.uid() AS uid)))))) AND ((acquisition_id IS NULL) OR (EXISTS ( SELECT 1
   FROM acquisitions acquisition
  WHERE ((acquisition.id = watch_events.acquisition_id) AND (acquisition.user_id = ( SELECT auth.uid() AS uid)))))) AND ((expense_id IS NULL) OR (EXISTS ( SELECT 1
   FROM expenses expense
  WHERE ((expense.id = watch_events.expense_id) AND (expense.user_id = ( SELECT auth.uid() AS uid))))))))
;
create policy "owner_delete" on public.watch_models as permissive for delete to authenticated
  using ((( SELECT auth.uid() AS uid) = user_id))
;
create policy "owner_insert" on public.watch_models as permissive for insert to authenticated
  with check ((( SELECT auth.uid() AS uid) = user_id))
;
create policy "owner_select" on public.watch_models as permissive for select to authenticated
  using ((( SELECT auth.uid() AS uid) = user_id))
;
create policy "owner_update" on public.watch_models as permissive for update to authenticated
  using ((( SELECT auth.uid() AS uid) = user_id))
  with check ((( SELECT auth.uid() AS uid) = user_id))
;
create policy "owner_delete" on public.watch_photo_links as permissive for delete to authenticated
  using ((( SELECT auth.uid() AS uid) = user_id))
;
create policy "owner_insert" on public.watch_photo_links as permissive for insert to authenticated
  with check (((( SELECT auth.uid() AS uid) = user_id) AND (EXISTS ( SELECT 1
   FROM watch_photos photo
  WHERE ((photo.id = watch_photo_links.photo_id) AND (photo.user_id = ( SELECT auth.uid() AS uid))))) AND (EXISTS ( SELECT 1
   FROM watches watch
  WHERE ((watch.id = watch_photo_links.watch_id) AND (watch.user_id = ( SELECT auth.uid() AS uid)))))))
;
create policy "owner_select" on public.watch_photo_links as permissive for select to authenticated
  using ((( SELECT auth.uid() AS uid) = user_id))
;
create policy "owner_update" on public.watch_photo_links as permissive for update to authenticated
  using ((( SELECT auth.uid() AS uid) = user_id))
  with check (((( SELECT auth.uid() AS uid) = user_id) AND (EXISTS ( SELECT 1
   FROM watch_photos photo
  WHERE ((photo.id = watch_photo_links.photo_id) AND (photo.user_id = ( SELECT auth.uid() AS uid))))) AND (EXISTS ( SELECT 1
   FROM watches watch
  WHERE ((watch.id = watch_photo_links.watch_id) AND (watch.user_id = ( SELECT auth.uid() AS uid)))))))
;
create policy "owner_delete_watch_photos" on public.watch_photos as permissive for delete to authenticated
  using ((( SELECT auth.uid() AS uid) = user_id))
;
create policy "owner_insert_watch_photos" on public.watch_photos as permissive for insert to authenticated
  with check (((( SELECT auth.uid() AS uid) = user_id) AND (((watch_id IS NOT NULL) AND (EXISTS ( SELECT 1
   FROM watches watch
  WHERE ((watch.id = watch_photos.watch_id) AND (watch.user_id = ( SELECT auth.uid() AS uid)))))) OR ((acquisition_id IS NOT NULL) AND (EXISTS ( SELECT 1
   FROM acquisitions acquisition
  WHERE ((acquisition.id = watch_photos.acquisition_id) AND (acquisition.user_id = ( SELECT auth.uid() AS uid)))))))))
;
create policy "owner_select_watch_photos" on public.watch_photos as permissive for select to authenticated
  using ((( SELECT auth.uid() AS uid) = user_id))
;
create policy "owner_update_watch_photos" on public.watch_photos as permissive for update to authenticated
  using ((( SELECT auth.uid() AS uid) = user_id))
  with check (((( SELECT auth.uid() AS uid) = user_id) AND (((watch_id IS NOT NULL) AND (EXISTS ( SELECT 1
   FROM watches watch
  WHERE ((watch.id = watch_photos.watch_id) AND (watch.user_id = ( SELECT auth.uid() AS uid)))))) OR ((acquisition_id IS NOT NULL) AND (EXISTS ( SELECT 1
   FROM acquisitions acquisition
  WHERE ((acquisition.id = watch_photos.acquisition_id) AND (acquisition.user_id = ( SELECT auth.uid() AS uid)))))))))
;
create policy "owner_delete" on public.watch_sources as permissive for delete to authenticated
  using ((( SELECT auth.uid() AS uid) = user_id))
;
create policy "owner_insert" on public.watch_sources as permissive for insert to authenticated
  with check (((( SELECT auth.uid() AS uid) = user_id) AND ((watch_id IS NULL) OR (EXISTS ( SELECT 1
   FROM watches watch
  WHERE ((watch.id = watch_sources.watch_id) AND (watch.user_id = ( SELECT auth.uid() AS uid)))))) AND ((acquisition_id IS NULL) OR (EXISTS ( SELECT 1
   FROM acquisitions acquisition
  WHERE ((acquisition.id = watch_sources.acquisition_id) AND (acquisition.user_id = ( SELECT auth.uid() AS uid))))))))
;
create policy "owner_select" on public.watch_sources as permissive for select to authenticated
  using ((( SELECT auth.uid() AS uid) = user_id))
;
create policy "owner_update" on public.watch_sources as permissive for update to authenticated
  using ((( SELECT auth.uid() AS uid) = user_id))
  with check (((( SELECT auth.uid() AS uid) = user_id) AND ((watch_id IS NULL) OR (EXISTS ( SELECT 1
   FROM watches watch
  WHERE ((watch.id = watch_sources.watch_id) AND (watch.user_id = ( SELECT auth.uid() AS uid)))))) AND ((acquisition_id IS NULL) OR (EXISTS ( SELECT 1
   FROM acquisitions acquisition
  WHERE ((acquisition.id = watch_sources.acquisition_id) AND (acquisition.user_id = ( SELECT auth.uid() AS uid))))))))
;
create policy "owners_delete_watches" on public.watches as permissive for delete to authenticated
  using ((( SELECT auth.uid() AS uid) = user_id))
;
create policy "owners_insert_watches" on public.watches as permissive for insert to authenticated
  with check ((( SELECT auth.uid() AS uid) = user_id))
;
create policy "owners_select_watches" on public.watches as permissive for select to authenticated
  using ((( SELECT auth.uid() AS uid) = user_id))
;
create policy "owners_update_watches" on public.watches as permissive for update to authenticated
  using ((( SELECT auth.uid() AS uid) = user_id))
  with check ((( SELECT auth.uid() AS uid) = user_id))
;
create policy "owner_delete_watch_photo_objects" on storage.objects as permissive for delete to authenticated
  using (((bucket_id = 'watch-photos'::text) AND ((storage.foldername(name))[1] = (( SELECT auth.uid() AS uid))::text)))
;
create policy "owner_insert_watch_photo_objects" on storage.objects as permissive for insert to authenticated
  with check (((bucket_id = 'watch-photos'::text) AND ((storage.foldername(name))[1] = (( SELECT auth.uid() AS uid))::text)))
;
create policy "owner_select_watch_photo_objects" on storage.objects as permissive for select to authenticated
  using (((bucket_id = 'watch-photos'::text) AND ((storage.foldername(name))[1] = (( SELECT auth.uid() AS uid))::text)))
;
create policy "owner_update_watch_photo_objects" on storage.objects as permissive for update to authenticated
  using (((bucket_id = 'watch-photos'::text) AND ((storage.foldername(name))[1] = (( SELECT auth.uid() AS uid))::text)))
  with check (((bucket_id = 'watch-photos'::text) AND ((storage.foldername(name))[1] = (( SELECT auth.uid() AS uid))::text)))
;

-- Explicit catalog privileges; independent of the target project's default privileges.
revoke all privileges on
  public.watches,
  public.maintenance_logs,
  public.brands,
  public.watch_photos,
  public.watch_models,
  public.movement_calibers,
  public.acquisitions,
  public.acquisition_items,
  public.expenses,
  public.expense_allocations,
  public.watch_events,
  public.watch_sources,
  public.watch_photo_links,
  public.watch_claims
from anon, authenticated, service_role;
grant select, insert, update, delete on
  public.watches,
  public.maintenance_logs,
  public.brands,
  public.watch_photos,
  public.watch_models,
  public.movement_calibers,
  public.acquisitions,
  public.acquisition_items,
  public.expenses,
  public.expense_allocations,
  public.watch_events,
  public.watch_sources,
  public.watch_photo_links,
  public.watch_claims
to authenticated;
grant all privileges on
  public.watches,
  public.maintenance_logs,
  public.brands,
  public.watch_photos,
  public.watch_models,
  public.movement_calibers,
  public.acquisitions,
  public.acquisition_items,
  public.expenses,
  public.expense_allocations,
  public.watch_events,
  public.watch_sources,
  public.watch_photo_links,
  public.watch_claims
to service_role;
revoke all privileges on sequence
  public.acquisition_items_id_seq,
  public.acquisitions_id_seq,
  public.brands_id_seq,
  public.expense_allocations_id_seq,
  public.expenses_id_seq,
  public.maintenance_logs_id_seq,
  public.movement_calibers_id_seq,
  public.watch_claims_id_seq,
  public.watch_events_id_seq,
  public.watch_models_id_seq,
  public.watch_photo_links_id_seq,
  public.watch_photos_id_seq,
  public.watch_sources_id_seq,
  public.watches_id_seq
from anon, authenticated, service_role;
grant usage on sequence
  public.acquisition_items_id_seq,
  public.acquisitions_id_seq,
  public.brands_id_seq,
  public.expense_allocations_id_seq,
  public.expenses_id_seq,
  public.maintenance_logs_id_seq,
  public.movement_calibers_id_seq,
  public.watch_claims_id_seq,
  public.watch_events_id_seq,
  public.watch_models_id_seq,
  public.watch_photo_links_id_seq,
  public.watch_photos_id_seq,
  public.watch_sources_id_seq,
  public.watches_id_seq
to authenticated;
grant usage on sequence
  public.acquisition_items_id_seq,
  public.acquisitions_id_seq,
  public.brands_id_seq,
  public.expense_allocations_id_seq,
  public.expenses_id_seq,
  public.maintenance_logs_id_seq,
  public.movement_calibers_id_seq,
  public.watch_claims_id_seq,
  public.watch_events_id_seq,
  public.watch_models_id_seq,
  public.watch_photo_links_id_seq,
  public.watch_photos_id_seq,
  public.watch_sources_id_seq,
  public.watches_id_seq
to service_role;

-- Private Storage bucket metadata. No storage objects are included.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types, type, versioning_status, avif_autodetection)
values ('watch-photos', 'watch-photos', false, 15728640, array['image/jpeg', 'image/png', 'image/webp', 'image/heic', 'image/heif']::text[], 'STANDARD', 'DISABLED', false);
