\set ON_ERROR_STOP on

-- Fila de Cadastro — especificação executável e protótipo local.
-- Este arquivo NÃO é uma migration e não deve ser aplicado ao projeto oficial.

create schema horoteca_private;

revoke all on schema horoteca_private from public, anon, authenticated;

create sequence public.watch_intake_number_seq
  as bigint
  start with 2
  increment by 1
  minvalue 2
  no maxvalue
  cache 1;

create table public.horoteca_user_roles (
  user_id uuid primary key references auth.users(id) on delete restrict,
  role text not null check (role in ('owner')),
  granted_at timestamptz not null default now(),
  granted_by uuid references auth.users(id) on delete restrict,
  notes text
);

create table public.watch_intakes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete restrict,
  intake_number bigint not null,
  intake_code text generated always as
    ('H' || case
      when intake_number < 1000 then lpad(intake_number::text, 3, '0')
      else intake_number::text
    end) stored,
  status text not null default 'new' check (status in (
    'new',
    'draft',
    'submitted_for_review_01',
    'review_01_in_progress',
    'review_01_corrections_requested',
    'review_01_approved',
    'submitted_for_review_02',
    'review_02_in_progress',
    'review_02_corrections_requested',
    'review_02_approved',
    'submitted_for_review_03',
    'review_03_in_progress',
    'review_03_corrections_requested',
    'review_03_approved',
    'awaiting_owner_approval',
    'owner_corrections_requested',
    'owner_approved',
    'finalization_ready',
    'finalizing',
    'finalization_failed',
    'completed',
    'cancelled'
  )),
  current_stage text not null default 'intake' check (current_stage in (
    'intake', 'review_01', 'review_02', 'review_03', 'owner',
    'finalization', 'completed', 'cancelled'
  )),
  version integer not null default 1 check (version > 0),
  title text,
  notes text,
  expected_item_count integer check (expected_item_count is null or expected_item_count > 0),
  identified_item_count integer not null default 0 check (identified_item_count >= 0),
  submitted_at timestamptz,
  owner_approved_at timestamptz,
  finalized_at timestamptz,
  cancelled_at timestamptz,
  finalization_key uuid,
  finalization_started_at timestamptz,
  finalization_error_code text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint watch_intakes_number_positive_check check (intake_number > 0),
  constraint watch_intakes_number_key unique (intake_number),
  constraint watch_intakes_code_key unique (intake_code),
  constraint watch_intakes_id_user_key unique (id, user_id),
  constraint watch_intakes_item_counts_check check (
    expected_item_count is null or identified_item_count <= expected_item_count
  ),
  constraint watch_intakes_terminal_dates_check check (
    (status <> 'completed' or finalized_at is not null)
    and (status <> 'cancelled' or cancelled_at is not null)
  )
);

create table public.watch_intake_documents (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete restrict,
  intake_id bigint not null,
  document_role text not null check (document_role in (
    'source_a', 'working_b', 'approved_b', 'support'
  )),
  provider text not null,
  provider_file_id text not null,
  url text,
  original_name text not null,
  display_name text,
  destination_folder_id text,
  provider_modified_at timestamptz,
  document_version integer not null default 1 check (document_version > 0),
  status text not null default 'active' check (status in (
    'active', 'superseded', 'inaccessible'
  )),
  previous_document_id bigint,
  source_document_id bigint,
  created_by uuid references auth.users(id) on delete restrict,
  extraction_prompt_version text,
  extracted_at timestamptz,
  content_hash text,
  is_accessible boolean,
  access_checked_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  notes text,
  provider_created_at timestamptz,
  registered_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint watch_intake_documents_intake_owner_fkey
    foreign key (intake_id, user_id)
    references public.watch_intakes(id, user_id) on delete restrict,
  constraint watch_intake_documents_previous_fkey
    foreign key (previous_document_id, user_id)
    references public.watch_intake_documents(id, user_id) on delete restrict,
  constraint watch_intake_documents_source_fkey
    foreign key (source_document_id, user_id)
    references public.watch_intake_documents(id, user_id) on delete restrict,
  constraint watch_intake_documents_id_user_key unique (id, user_id),
  constraint watch_intake_documents_provider_version_key unique (
    intake_id, document_role, provider, provider_file_id, document_version
  )
);

create unique index watch_intake_documents_one_source_a_uidx
  on public.watch_intake_documents (intake_id)
  where document_role = 'source_a';

create table public.watch_intake_extractions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete restrict,
  intake_id bigint not null,
  source_document_id bigint not null,
  provider text not null,
  agent_name text,
  model_name text,
  model_version text,
  prompt_name text,
  prompt_version text,
  status text not null check (status in ('started', 'completed', 'failed')),
  structured_snapshot jsonb,
  raw_response_reference text,
  error_code text,
  error_summary text,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  constraint watch_intake_extractions_intake_owner_fkey
    foreign key (intake_id, user_id)
    references public.watch_intakes(id, user_id) on delete restrict,
  constraint watch_intake_extractions_document_owner_fkey
    foreign key (source_document_id, user_id)
    references public.watch_intake_documents(id, user_id) on delete restrict,
  constraint watch_intake_extractions_id_user_key unique (id, user_id)
);

create table public.watch_intake_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete restrict,
  intake_id bigint not null,
  acquisition_id bigint,
  item_sequence integer not null check (item_sequence > 0),
  visual_position text,
  order_number text,
  order_item_number integer,
  marketplace_item_id text,
  candidate_horoteca_code text,
  candidate_brand text,
  candidate_model text,
  candidate_reference_number text,
  candidate_movement_type text,
  candidate_serial_number text,
  candidate_case_code text,
  candidate_dial_code text,
  candidate_watch_data jsonb not null default '{}'::jsonb,
  candidate_brand_id bigint references public.brands(id) on delete set null,
  candidate_watch_model_id bigint references public.watch_models(id) on delete set null,
  candidate_movement_caliber_id bigint references public.movement_calibers(id) on delete set null,
  brand_match_status text not null default 'unreviewed' check (brand_match_status in (
    'unreviewed', 'exact_match', 'explicit_new', 'ambiguous', 'not_applicable'
  )),
  model_match_status text not null default 'unreviewed' check (model_match_status in (
    'unreviewed', 'exact_match', 'explicit_new', 'ambiguous', 'not_applicable'
  )),
  caliber_match_status text not null default 'unreviewed' check (caliber_match_status in (
    'unreviewed', 'exact_match', 'explicit_new', 'ambiguous', 'not_applicable'
  )),
  final_watch_id bigint references public.watches(id) on delete restrict,
  final_horoteca_code text,
  finalized_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint watch_intake_items_intake_owner_fkey
    foreign key (intake_id, user_id)
    references public.watch_intakes(id, user_id) on delete restrict,
  constraint watch_intake_items_id_user_key unique (id, user_id),
  constraint watch_intake_items_sequence_key unique (intake_id, item_sequence),
  constraint watch_intake_items_final_watch_key unique (final_watch_id),
  constraint watch_intake_items_finalization_check check (
    (final_watch_id is null and finalized_at is null)
    or (final_watch_id is not null and finalized_at is not null)
  )
);

create table public.watch_intake_acquisitions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete restrict,
  intake_id bigint not null,
  marketplace text,
  seller_name text,
  order_number text,
  purchase_date date,
  purchase_payment_date date,
  taxes_payment_date date,
  shipped_date date,
  estimated_delivery_date date,
  received_date date,
  payment_method text,
  carrier text,
  tracking_number text,
  source_document_id bigint,
  candidate_acquisition_id bigint references public.acquisitions(id) on delete set null,
  match_status text not null default 'unreviewed' check (match_status in (
    'unreviewed', 'exact_match', 'explicit_new', 'ambiguous', 'not_applicable'
  )),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint watch_intake_acquisitions_intake_owner_fkey
    foreign key (intake_id, user_id)
    references public.watch_intakes(id, user_id) on delete restrict,
  constraint watch_intake_acquisitions_document_owner_fkey
    foreign key (source_document_id, user_id)
    references public.watch_intake_documents(id, user_id) on delete restrict,
  constraint watch_intake_acquisitions_id_user_key unique (id, user_id)
);

create table public.watch_intake_expenses (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete restrict,
  intake_id bigint not null,
  acquisition_id bigint,
  item_id bigint,
  category text not null check (category in (
    'product', 'freight', 'tax', 'fee', 'carrier', 'maintenance',
    'parts', 'strap', 'other'
  )),
  description text,
  expense_date date,
  currency text,
  amount_original numeric,
  exchange_rate numeric,
  amount_brl numeric,
  is_shared boolean not null default false,
  allocation_method text check (allocation_method in (
    'individual', 'proportional', 'equal', 'manual'
  )),
  source_document_id bigint,
  source_reference text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint watch_intake_expenses_intake_owner_fkey
    foreign key (intake_id, user_id)
    references public.watch_intakes(id, user_id) on delete restrict,
  constraint watch_intake_expenses_acquisition_owner_fkey
    foreign key (acquisition_id, user_id)
    references public.watch_intake_acquisitions(id, user_id) on delete restrict,
  constraint watch_intake_expenses_item_owner_fkey
    foreign key (item_id, user_id)
    references public.watch_intake_items(id, user_id) on delete restrict,
  constraint watch_intake_expenses_document_owner_fkey
    foreign key (source_document_id, user_id)
    references public.watch_intake_documents(id, user_id) on delete restrict,
  constraint watch_intake_expenses_id_user_key unique (id, user_id),
  constraint watch_intake_expenses_amounts_check check (
    (amount_original is null or amount_original >= 0)
    and (exchange_rate is null or exchange_rate > 0)
    and (amount_brl is null or amount_brl >= 0)
  )
);

alter table public.watch_intake_items
  add constraint watch_intake_items_acquisition_owner_fkey
  foreign key (acquisition_id, user_id)
  references public.watch_intake_acquisitions(id, user_id) on delete restrict;

create table public.watch_intake_expense_allocations (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete restrict,
  intake_id bigint not null,
  expense_id bigint not null,
  item_id bigint not null,
  allocation_basis text,
  allocation_weight numeric,
  unrounded_amount_brl numeric,
  rounded_up_amount_brl numeric,
  reconciliation_adjustment_brl numeric not null default 0,
  final_amount_brl numeric,
  approved_revision_id bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint watch_intake_allocations_intake_owner_fkey
    foreign key (intake_id, user_id)
    references public.watch_intakes(id, user_id) on delete restrict,
  constraint watch_intake_allocations_expense_owner_fkey
    foreign key (expense_id, user_id)
    references public.watch_intake_expenses(id, user_id) on delete restrict,
  constraint watch_intake_allocations_item_owner_fkey
    foreign key (item_id, user_id)
    references public.watch_intake_items(id, user_id) on delete restrict,
  constraint watch_intake_allocations_id_user_key unique (id, user_id),
  constraint watch_intake_allocations_expense_item_key unique (expense_id, item_id),
  constraint watch_intake_allocations_amounts_check check (
    (allocation_weight is null or allocation_weight >= 0)
    and (unrounded_amount_brl is null or unrounded_amount_brl >= 0)
    and (rounded_up_amount_brl is null or rounded_up_amount_brl >= 0)
    and (final_amount_brl is null or final_amount_brl >= 0)
    and (
      final_amount_brl is null
      or rounded_up_amount_brl is not null
      and final_amount_brl = rounded_up_amount_brl + reconciliation_adjustment_brl
    )
  )
);

create table public.watch_intake_sources (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete restrict,
  intake_id bigint not null,
  item_id bigint,
  source_document_id bigint,
  source_type text not null,
  title text,
  url text,
  evidence_classification text not null check (evidence_classification in (
    'document_confirmed', 'seller_statement', 'visual_observation',
    'researched', 'estimated', 'missing', 'inconsistent'
  )),
  confidence_percent integer check (confidence_percent between 0 and 100),
  excerpt text,
  accessed_at timestamptz,
  notes text,
  created_at timestamptz not null default now(),
  constraint watch_intake_sources_intake_owner_fkey
    foreign key (intake_id, user_id)
    references public.watch_intakes(id, user_id) on delete restrict,
  constraint watch_intake_sources_item_owner_fkey
    foreign key (item_id, user_id)
    references public.watch_intake_items(id, user_id) on delete restrict,
  constraint watch_intake_sources_document_owner_fkey
    foreign key (source_document_id, user_id)
    references public.watch_intake_documents(id, user_id) on delete restrict,
  constraint watch_intake_sources_id_user_key unique (id, user_id)
);

create table public.watch_intake_claims (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete restrict,
  intake_id bigint not null,
  item_id bigint,
  source_id bigint,
  field_name text not null check (btrim(field_name) <> ''),
  asserted_value text not null check (btrim(asserted_value) <> ''),
  normalized_value jsonb,
  asserted_by_type text not null check (asserted_by_type in (
    'document', 'seller', 'gemini', 'agent', 'research',
    'visual_observation', 'owner'
  )),
  evidence_classification text not null check (evidence_classification in (
    'document_confirmed', 'seller_statement', 'visual_observation',
    'researched', 'estimated', 'missing', 'inconsistent'
  )),
  verification_status text not null default 'pending' check (verification_status in (
    'pending', 'accepted', 'rejected', 'superseded'
  )),
  confidence_percent integer check (confidence_percent between 0 and 100),
  context text,
  reviewed_in_revision_id bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint watch_intake_claims_intake_owner_fkey
    foreign key (intake_id, user_id)
    references public.watch_intakes(id, user_id) on delete restrict,
  constraint watch_intake_claims_item_owner_fkey
    foreign key (item_id, user_id)
    references public.watch_intake_items(id, user_id) on delete restrict,
  constraint watch_intake_claims_source_owner_fkey
    foreign key (source_id, user_id)
    references public.watch_intake_sources(id, user_id) on delete restrict,
  constraint watch_intake_claims_id_user_key unique (id, user_id)
);

create table public.watch_intake_photos (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete restrict,
  intake_id bigint not null,
  source_document_id bigint,
  provider text not null,
  provider_file_id text,
  original_url text,
  storage_path text,
  origin_type text,
  visual_position text,
  evidence_classification text check (evidence_classification in (
    'document_confirmed', 'seller_statement', 'visual_observation',
    'researched', 'estimated', 'missing', 'inconsistent'
  )),
  display_order integer check (display_order is null or display_order > 0),
  is_cover_candidate boolean not null default false,
  copy_status text not null default 'not_requested' check (copy_status in (
    'not_requested', 'pending', 'copied', 'failed', 'not_applicable'
  )),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint watch_intake_photos_intake_owner_fkey
    foreign key (intake_id, user_id)
    references public.watch_intakes(id, user_id) on delete restrict,
  constraint watch_intake_photos_document_owner_fkey
    foreign key (source_document_id, user_id)
    references public.watch_intake_documents(id, user_id) on delete restrict,
  constraint watch_intake_photos_id_user_key unique (id, user_id),
  constraint watch_intake_photos_provider_file_key unique (intake_id, provider, provider_file_id)
);

create table public.watch_intake_photo_links (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete restrict,
  intake_id bigint not null,
  photo_id bigint not null,
  item_id bigint not null,
  relation_type text not null default 'evidence' check (relation_type in (
    'evidence', 'display', 'cover'
  )),
  created_at timestamptz not null default now(),
  constraint watch_intake_photo_links_intake_owner_fkey
    foreign key (intake_id, user_id)
    references public.watch_intakes(id, user_id) on delete restrict,
  constraint watch_intake_photo_links_photo_owner_fkey
    foreign key (photo_id, user_id)
    references public.watch_intake_photos(id, user_id) on delete restrict,
  constraint watch_intake_photo_links_item_owner_fkey
    foreign key (item_id, user_id)
    references public.watch_intake_items(id, user_id) on delete restrict,
  constraint watch_intake_photo_links_photo_item_key unique (photo_id, item_id)
);

create table public.watch_intake_revisions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete restrict,
  intake_id bigint not null,
  revision_type smallint not null check (revision_type between 1 and 3),
  pass_number integer not null check (pass_number > 0),
  status text not null check (status in (
    'started', 'corrections_requested', 'approved', 'rejected', 'invalidated'
  )),
  initial_intake_version integer not null check (initial_intake_version > 0),
  reviewed_intake_version integer check (reviewed_intake_version > 0),
  source_document_id bigint not null,
  working_document_id bigint,
  reviewer_id uuid not null references auth.users(id) on delete restrict,
  execution_mode text not null check (execution_mode in (
    'human', 'assisted', 'server_agent'
  )),
  agent_name text,
  model_name text,
  model_version text,
  prompt_name text,
  prompt_version text,
  checklist_version text not null,
  checklist_result jsonb not null default '{}'::jsonb,
  opinion text,
  immutable_snapshot jsonb,
  snapshot_hash text,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  decision_at timestamptz,
  created_at timestamptz not null default now(),
  constraint watch_intake_revisions_intake_owner_fkey
    foreign key (intake_id, user_id)
    references public.watch_intakes(id, user_id) on delete restrict,
  constraint watch_intake_revisions_source_owner_fkey
    foreign key (source_document_id, user_id)
    references public.watch_intake_documents(id, user_id) on delete restrict,
  constraint watch_intake_revisions_working_owner_fkey
    foreign key (working_document_id, user_id)
    references public.watch_intake_documents(id, user_id) on delete restrict,
  constraint watch_intake_revisions_id_user_key unique (id, user_id),
  constraint watch_intake_revisions_pass_key unique (intake_id, revision_type, pass_number),
  constraint watch_intake_revisions_completion_check check (
    status = 'started'
    or completed_at is not null and decision_at is not null
  )
);

alter table public.watch_intake_expense_allocations
  add constraint watch_intake_allocations_revision_owner_fkey
  foreign key (approved_revision_id, user_id)
  references public.watch_intake_revisions(id, user_id) on delete restrict;

alter table public.watch_intake_claims
  add constraint watch_intake_claims_revision_owner_fkey
  foreign key (reviewed_in_revision_id, user_id)
  references public.watch_intake_revisions(id, user_id) on delete restrict;

create table public.watch_intake_findings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete restrict,
  intake_id bigint not null,
  revision_id bigint not null,
  item_id bigint,
  field_name text,
  category text not null check (category in (
    'omission', 'item_swap', 'invention', 'identifier', 'date', 'value',
    'allocation', 'source', 'classification', 'image', 'duplicate',
    'technical', 'historical_scope'
  )),
  severity text not null check (severity in ('info', 'warning', 'blocking')),
  description text not null check (btrim(description) <> ''),
  source_reference text,
  status text not null default 'open' check (status in (
    'open', 'resolved', 'accepted_pending', 'superseded'
  )),
  resolution text,
  resolved_by uuid references auth.users(id) on delete restrict,
  resolved_in_intake_version integer check (resolved_in_intake_version > 0),
  created_at timestamptz not null default now(),
  resolved_at timestamptz,
  constraint watch_intake_findings_intake_owner_fkey
    foreign key (intake_id, user_id)
    references public.watch_intakes(id, user_id) on delete restrict,
  constraint watch_intake_findings_revision_owner_fkey
    foreign key (revision_id, user_id)
    references public.watch_intake_revisions(id, user_id) on delete restrict,
  constraint watch_intake_findings_item_owner_fkey
    foreign key (item_id, user_id)
    references public.watch_intake_items(id, user_id) on delete restrict,
  constraint watch_intake_findings_id_user_key unique (id, user_id),
  constraint watch_intake_findings_resolution_check check (
    status not in ('resolved', 'accepted_pending')
    or resolution is not null and resolved_by is not null and resolved_at is not null
  )
);

create table public.watch_intake_owner_decisions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete restrict,
  intake_id bigint not null,
  action text not null check (action in ('approve', 'request_correction', 'cancel')),
  decided_by uuid not null references auth.users(id) on delete restrict,
  intake_version integer not null check (intake_version > 0),
  document_b_id bigint,
  immutable_snapshot jsonb not null,
  snapshot_hash text not null,
  notes text,
  decided_at timestamptz not null default now(),
  constraint watch_intake_owner_decisions_intake_owner_fkey
    foreign key (intake_id, user_id)
    references public.watch_intakes(id, user_id) on delete restrict,
  constraint watch_intake_owner_decisions_document_owner_fkey
    foreign key (document_b_id, user_id)
    references public.watch_intake_documents(id, user_id) on delete restrict,
  constraint watch_intake_owner_decisions_id_user_key unique (id, user_id)
);

create table public.watch_intake_transitions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete restrict,
  intake_id bigint not null,
  from_status text,
  to_status text not null,
  intake_version integer not null check (intake_version > 0),
  actor_id uuid references auth.users(id) on delete restrict,
  actor_type text not null check (actor_type in (
    'owner', 'user', 'server_agent', 'system', 'historical_import'
  )),
  reason text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint watch_intake_transitions_intake_owner_fkey
    foreign key (intake_id, user_id)
    references public.watch_intakes(id, user_id) on delete restrict,
  constraint watch_intake_transitions_id_user_key unique (id, user_id)
);

create table public.watch_intake_finalizations (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete restrict,
  intake_id bigint not null,
  idempotency_key uuid not null,
  requested_intake_version integer not null check (requested_intake_version > 0),
  status text not null check (status in ('requested', 'running', 'completed', 'failed')),
  requested_by uuid not null references auth.users(id) on delete restrict,
  requested_at timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz,
  result jsonb,
  error_code text,
  error_summary text,
  created_at timestamptz not null default now(),
  constraint watch_intake_finalizations_intake_owner_fkey
    foreign key (intake_id, user_id)
    references public.watch_intakes(id, user_id) on delete restrict,
  constraint watch_intake_finalizations_idempotency_key unique (idempotency_key),
  constraint watch_intake_finalizations_intake_key unique (intake_id, idempotency_key),
  constraint watch_intake_finalizations_id_user_key unique (id, user_id),
  constraint watch_intake_finalizations_result_check check (
    (status = 'completed' and completed_at is not null and result is not null)
    or status <> 'completed'
  )
);

create table horoteca_private.allowed_intake_transitions (
  from_status text not null,
  to_status text not null,
  primary key (from_status, to_status)
);

insert into horoteca_private.allowed_intake_transitions (from_status, to_status)
values
  ('new', 'draft'),
  ('draft', 'submitted_for_review_01'),
  ('submitted_for_review_01', 'review_01_in_progress'),
  ('review_01_in_progress', 'review_01_corrections_requested'),
  ('review_01_in_progress', 'review_01_approved'),
  ('review_01_corrections_requested', 'draft'),
  ('review_01_approved', 'submitted_for_review_02'),
  ('submitted_for_review_02', 'review_02_in_progress'),
  ('review_02_in_progress', 'review_02_corrections_requested'),
  ('review_02_in_progress', 'review_02_approved'),
  ('review_02_corrections_requested', 'draft'),
  ('review_02_approved', 'submitted_for_review_03'),
  ('submitted_for_review_03', 'review_03_in_progress'),
  ('review_03_in_progress', 'review_03_corrections_requested'),
  ('review_03_in_progress', 'review_03_approved'),
  ('review_03_corrections_requested', 'draft'),
  ('review_03_approved', 'awaiting_owner_approval'),
  ('awaiting_owner_approval', 'owner_corrections_requested'),
  ('awaiting_owner_approval', 'owner_approved'),
  ('owner_corrections_requested', 'draft'),
  ('owner_approved', 'finalization_ready'),
  ('finalization_ready', 'finalizing'),
  ('finalizing', 'finalization_failed'),
  ('finalizing', 'completed'),
  ('finalization_failed', 'finalization_ready');

create function horoteca_private.prevent_immutable_audit_mutation()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  raise exception '% is append-only', tg_table_name using errcode = '55000';
end;
$$;

create function horoteca_private.protect_source_document_identity()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if old.document_role = 'source_a' and (
    new.intake_id is distinct from old.intake_id
    or new.user_id is distinct from old.user_id
    or new.document_role is distinct from old.document_role
    or new.provider is distinct from old.provider
    or new.provider_file_id is distinct from old.provider_file_id
    or new.original_name is distinct from old.original_name
    or new.provider_created_at is distinct from old.provider_created_at
  ) then
    raise exception 'Documento A é logicamente imutável' using errcode = '55000';
  end if;

  if new.document_role = 'approved_b' and old.document_role <> 'approved_b' then
    raise exception 'approved_b exige operação autorizada do proprietário'
      using errcode = '42501';
  end if;

  return new;
end;
$$;

create function horoteca_private.assign_intake_identity()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if current_user = 'authenticated' then
    if (select auth.uid()) is null then
      raise exception 'Sessão autenticada obrigatória' using errcode = '28000';
    end if;

    new.user_id := (select auth.uid());
    new.intake_number := nextval('public.watch_intake_number_seq');
    new.status := 'new';
    new.current_stage := 'intake';
    new.version := 1;
    new.owner_approved_at := null;
    new.finalized_at := null;
    new.cancelled_at := null;
    new.finalization_key := null;
    new.finalization_started_at := null;
    new.finalization_error_code := null;
  end if;

  return new;
end;
$$;

create function horoteca_private.protect_intake_control_fields()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if current_user = 'authenticated' and (
    new.user_id is distinct from old.user_id
    or new.intake_number is distinct from old.intake_number
    or new.status is distinct from old.status
    or new.current_stage is distinct from old.current_stage
    or new.version is distinct from old.version
    or new.owner_approved_at is distinct from old.owner_approved_at
    or new.finalized_at is distinct from old.finalized_at
    or new.cancelled_at is distinct from old.cancelled_at
    or new.finalization_key is distinct from old.finalization_key
    or new.finalization_started_at is distinct from old.finalization_started_at
    or new.finalization_error_code is distinct from old.finalization_error_code
  ) then
    raise exception 'Campos de controle exigem operação de transição autorizada'
      using errcode = '42501';
  end if;

  return new;
end;
$$;

create function public.is_horoteca_owner()
returns boolean
language sql
stable
security invoker
set search_path = ''
as $$
  select exists (
    select 1
    from public.horoteca_user_roles role_assignment
    where role_assignment.user_id = (select auth.uid())
      and role_assignment.role = 'owner'
  )
$$;

revoke all on function public.is_horoteca_owner() from public, anon;
grant execute on function public.is_horoteca_owner() to authenticated;

create trigger watch_intakes_set_updated_at
before update on public.watch_intakes
for each row execute function public.set_updated_at();

create trigger watch_intakes_assign_identity
before insert on public.watch_intakes
for each row execute function horoteca_private.assign_intake_identity();

create trigger watch_intakes_protect_control_fields
before update on public.watch_intakes
for each row execute function horoteca_private.protect_intake_control_fields();

create trigger watch_intake_documents_protect_source
before update on public.watch_intake_documents
for each row execute function horoteca_private.protect_source_document_identity();

create trigger watch_intake_items_set_updated_at
before update on public.watch_intake_items
for each row execute function public.set_updated_at();

create trigger watch_intake_acquisitions_set_updated_at
before update on public.watch_intake_acquisitions
for each row execute function public.set_updated_at();

create trigger watch_intake_expenses_set_updated_at
before update on public.watch_intake_expenses
for each row execute function public.set_updated_at();

create trigger watch_intake_expense_allocations_set_updated_at
before update on public.watch_intake_expense_allocations
for each row execute function public.set_updated_at();

create trigger watch_intake_claims_set_updated_at
before update on public.watch_intake_claims
for each row execute function public.set_updated_at();

create trigger watch_intake_photos_set_updated_at
before update on public.watch_intake_photos
for each row execute function public.set_updated_at();

create trigger watch_intake_owner_decisions_immutable
before update or delete on public.watch_intake_owner_decisions
for each row execute function horoteca_private.prevent_immutable_audit_mutation();

create trigger watch_intake_transitions_immutable
before update or delete on public.watch_intake_transitions
for each row execute function horoteca_private.prevent_immutable_audit_mutation();

create trigger watch_intake_revisions_completed_immutable
before update or delete on public.watch_intake_revisions
for each row
when (old.status <> 'started')
execute function horoteca_private.prevent_immutable_audit_mutation();

create index horoteca_user_roles_role_idx on public.horoteca_user_roles (role);
create index watch_intakes_user_id_idx on public.watch_intakes (user_id);
create index watch_intakes_user_status_idx on public.watch_intakes (user_id, status);
create index watch_intake_documents_user_id_idx on public.watch_intake_documents (user_id);
create index watch_intake_documents_intake_id_idx on public.watch_intake_documents (intake_id);
create index watch_intake_extractions_user_id_idx on public.watch_intake_extractions (user_id);
create index watch_intake_extractions_intake_id_idx on public.watch_intake_extractions (intake_id);
create index watch_intake_items_user_id_idx on public.watch_intake_items (user_id);
create index watch_intake_items_intake_id_idx on public.watch_intake_items (intake_id);
create index watch_intake_acquisitions_user_id_idx on public.watch_intake_acquisitions (user_id);
create index watch_intake_acquisitions_intake_id_idx on public.watch_intake_acquisitions (intake_id);
create index watch_intake_expenses_user_id_idx on public.watch_intake_expenses (user_id);
create index watch_intake_expenses_intake_id_idx on public.watch_intake_expenses (intake_id);
create index watch_intake_allocations_user_id_idx on public.watch_intake_expense_allocations (user_id);
create index watch_intake_allocations_intake_id_idx on public.watch_intake_expense_allocations (intake_id);
create index watch_intake_sources_user_id_idx on public.watch_intake_sources (user_id);
create index watch_intake_sources_intake_id_idx on public.watch_intake_sources (intake_id);
create index watch_intake_claims_user_id_idx on public.watch_intake_claims (user_id);
create index watch_intake_claims_intake_id_idx on public.watch_intake_claims (intake_id);
create index watch_intake_photos_user_id_idx on public.watch_intake_photos (user_id);
create index watch_intake_photos_intake_id_idx on public.watch_intake_photos (intake_id);
create index watch_intake_photo_links_user_id_idx on public.watch_intake_photo_links (user_id);
create index watch_intake_photo_links_intake_id_idx on public.watch_intake_photo_links (intake_id);
create index watch_intake_revisions_user_id_idx on public.watch_intake_revisions (user_id);
create index watch_intake_revisions_intake_id_idx on public.watch_intake_revisions (intake_id);
create index watch_intake_findings_user_id_idx on public.watch_intake_findings (user_id);
create index watch_intake_findings_intake_status_idx on public.watch_intake_findings (intake_id, status);
create index watch_intake_owner_decisions_user_id_idx on public.watch_intake_owner_decisions (user_id);
create index watch_intake_owner_decisions_intake_id_idx on public.watch_intake_owner_decisions (intake_id);
create index watch_intake_transitions_user_id_idx on public.watch_intake_transitions (user_id);
create index watch_intake_transitions_intake_id_idx on public.watch_intake_transitions (intake_id, created_at);
create index watch_intake_finalizations_user_id_idx on public.watch_intake_finalizations (user_id);
create index watch_intake_finalizations_intake_id_idx on public.watch_intake_finalizations (intake_id);

alter table public.horoteca_user_roles enable row level security;
alter table public.watch_intakes enable row level security;
alter table public.watch_intake_documents enable row level security;
alter table public.watch_intake_extractions enable row level security;
alter table public.watch_intake_items enable row level security;
alter table public.watch_intake_acquisitions enable row level security;
alter table public.watch_intake_expenses enable row level security;
alter table public.watch_intake_expense_allocations enable row level security;
alter table public.watch_intake_sources enable row level security;
alter table public.watch_intake_claims enable row level security;
alter table public.watch_intake_photos enable row level security;
alter table public.watch_intake_photo_links enable row level security;
alter table public.watch_intake_revisions enable row level security;
alter table public.watch_intake_findings enable row level security;
alter table public.watch_intake_owner_decisions enable row level security;
alter table public.watch_intake_transitions enable row level security;
alter table public.watch_intake_finalizations enable row level security;

create policy owner_select on public.horoteca_user_roles
for select to authenticated
using ((select auth.uid()) = user_id);

-- Tabelas editáveis no staging. Nenhuma tabela recebe política direta de
-- DELETE: cancelamento e histórico nunca são implementados como exclusão.
do $policies$
declare
  table_name text;
begin
  foreach table_name in array array[
    'watch_intakes',
    'watch_intake_items',
    'watch_intake_acquisitions',
    'watch_intake_expenses',
    'watch_intake_expense_allocations',
    'watch_intake_sources',
    'watch_intake_claims',
    'watch_intake_photos',
    'watch_intake_photo_links',
    'watch_intake_findings'
  ]
  loop
    execute format(
      'create policy owner_select on public.%I for select to authenticated using ((select auth.uid()) = user_id)',
      table_name
    );
    execute format(
      'create policy owner_insert on public.%I for insert to authenticated with check ((select auth.uid()) = user_id)',
      table_name
    );
    execute format(
      'create policy owner_update on public.%I for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id)',
      table_name
    );
  end loop;
end;
$policies$;

create policy owner_select on public.watch_intake_documents
for select to authenticated using ((select auth.uid()) = user_id);
create policy owner_insert on public.watch_intake_documents
for insert to authenticated
with check ((select auth.uid()) = user_id and document_role <> 'approved_b');
create policy owner_update on public.watch_intake_documents
for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy owner_select on public.watch_intake_extractions
for select to authenticated using ((select auth.uid()) = user_id);
create policy owner_insert on public.watch_intake_extractions
for insert to authenticated with check ((select auth.uid()) = user_id);
create policy owner_update on public.watch_intake_extractions
for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy owner_select on public.watch_intake_revisions
for select to authenticated using ((select auth.uid()) = user_id);
create policy owner_insert on public.watch_intake_revisions
for insert to authenticated with check ((select auth.uid()) = user_id);
create policy owner_update on public.watch_intake_revisions
for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy owner_select on public.watch_intake_owner_decisions
for select to authenticated using ((select auth.uid()) = user_id);
create policy owner_select on public.watch_intake_transitions
for select to authenticated using ((select auth.uid()) = user_id);
create policy owner_select on public.watch_intake_finalizations
for select to authenticated using ((select auth.uid()) = user_id);

revoke all privileges on
  public.horoteca_user_roles,
  public.watch_intakes,
  public.watch_intake_documents,
  public.watch_intake_extractions,
  public.watch_intake_items,
  public.watch_intake_acquisitions,
  public.watch_intake_expenses,
  public.watch_intake_expense_allocations,
  public.watch_intake_sources,
  public.watch_intake_claims,
  public.watch_intake_photos,
  public.watch_intake_photo_links,
  public.watch_intake_revisions,
  public.watch_intake_findings,
  public.watch_intake_owner_decisions,
  public.watch_intake_transitions,
  public.watch_intake_finalizations
from anon, authenticated;

grant select on public.horoteca_user_roles to authenticated;

grant select, insert, update, delete on
  public.watch_intakes,
  public.watch_intake_documents,
  public.watch_intake_extractions,
  public.watch_intake_items,
  public.watch_intake_acquisitions,
  public.watch_intake_expenses,
  public.watch_intake_expense_allocations,
  public.watch_intake_sources,
  public.watch_intake_claims,
  public.watch_intake_photos,
  public.watch_intake_photo_links,
  public.watch_intake_revisions,
  public.watch_intake_findings,
  public.watch_intake_owner_decisions,
  public.watch_intake_transitions,
  public.watch_intake_finalizations
to authenticated;

revoke all privileges on
  public.watch_intake_number_seq,
  public.watch_intakes_id_seq,
  public.watch_intake_documents_id_seq,
  public.watch_intake_extractions_id_seq,
  public.watch_intake_items_id_seq,
  public.watch_intake_acquisitions_id_seq,
  public.watch_intake_expenses_id_seq,
  public.watch_intake_expense_allocations_id_seq,
  public.watch_intake_sources_id_seq,
  public.watch_intake_claims_id_seq,
  public.watch_intake_photos_id_seq,
  public.watch_intake_photo_links_id_seq,
  public.watch_intake_revisions_id_seq,
  public.watch_intake_findings_id_seq,
  public.watch_intake_owner_decisions_id_seq,
  public.watch_intake_transitions_id_seq,
  public.watch_intake_finalizations_id_seq
from anon;
grant usage, select on
  public.watch_intake_number_seq,
  public.watch_intakes_id_seq,
  public.watch_intake_documents_id_seq,
  public.watch_intake_extractions_id_seq,
  public.watch_intake_items_id_seq,
  public.watch_intake_acquisitions_id_seq,
  public.watch_intake_expenses_id_seq,
  public.watch_intake_expense_allocations_id_seq,
  public.watch_intake_sources_id_seq,
  public.watch_intake_claims_id_seq,
  public.watch_intake_photos_id_seq,
  public.watch_intake_photo_links_id_seq,
  public.watch_intake_revisions_id_seq,
  public.watch_intake_findings_id_seq,
  public.watch_intake_owner_decisions_id_seq,
  public.watch_intake_transitions_id_seq,
  public.watch_intake_finalizations_id_seq
to authenticated;

revoke all on all functions in schema horoteca_private from public, anon, authenticated;
revoke all on all tables in schema horoteca_private from public, anon, authenticated;
