-- Applied to project nlkhbhgzscpdistzuyod on 2026-08-06.
-- Preserves the existing watches and maintenance history.

alter table public.watches
  add column if not exists horoteca_code text,
  add column if not exists order_number text,
  add column if not exists order_item_number integer,
  add column if not exists marketplace text,
  add column if not exists marketplace_item_id text,
  add column if not exists seller_name text,
  add column if not exists purchase_currency text,
  add column if not exists purchase_amount_original numeric(14,2),
  add column if not exists purchase_total_brl numeric(14,2),
  add column if not exists payment_method text,
  add column if not exists estimated_value numeric(14,2),
  add column if not exists estimated_value_date date,
  add column if not exists manufacture_year integer,
  add column if not exists movement_caliber text,
  add column if not exists condition text;

create unique index if not exists watches_user_horoteca_code_uidx
  on public.watches (user_id, horoteca_code)
  where horoteca_code is not null;

alter table public.maintenance_logs
  add column if not exists user_id uuid references auth.users(id),
  add column if not exists event_type text not null default 'manutencao',
  add column if not exists expense_category text,
  add column if not exists currency text not null default 'BRL',
  add column if not exists amount_original numeric(14,2),
  add column if not exists amount_brl numeric(14,2),
  add column if not exists event_date date,
  add column if not exists notes text;

create table if not exists public.brands (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id),
  name text not null,
  country text,
  founded_year integer,
  founder text,
  history text,
  milestones text,
  technologies text,
  curiosities text,
  logo_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, name)
);

create table if not exists public.watch_photos (
  id bigint generated by default as identity primary key,
  watch_id bigint not null references public.watches(id) on delete cascade,
  user_id uuid not null default auth.uid() references auth.users(id),
  storage_path text not null,
  caption text,
  is_cover boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  unique (user_id, storage_path)
);

update public.maintenance_logs ml set user_id = w.user_id
from public.watches w where ml.watch_id = w.id and ml.user_id is null;
update public.maintenance_logs set amount_brl = cost
where amount_brl is null and cost is not null;
update public.maintenance_logs set amount_original = coalesce(amount_brl, cost)
where amount_original is null;
alter table public.maintenance_logs alter column user_id set default auth.uid();
alter table public.maintenance_logs alter column user_id set not null;

alter table public.brands enable row level security;
alter table public.watch_photos enable row level security;
grant select, insert, update, delete on public.brands, public.watch_photos to authenticated;
grant usage, select on sequence public.brands_id_seq, public.watch_photos_id_seq to authenticated;

create policy "owner_select_brands" on public.brands for select to authenticated
using ((select auth.uid()) = user_id);
create policy "owner_insert_brands" on public.brands for insert to authenticated
with check ((select auth.uid()) = user_id);
create policy "owner_update_brands" on public.brands for update to authenticated
using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "owner_delete_brands" on public.brands for delete to authenticated
using ((select auth.uid()) = user_id);

create policy "owner_select_watch_photos" on public.watch_photos for select to authenticated
using ((select auth.uid()) = user_id);
create policy "owner_insert_watch_photos" on public.watch_photos for insert to authenticated
with check ((select auth.uid()) = user_id and exists
  (select 1 from public.watches w where w.id = watch_id and w.user_id = (select auth.uid())));
create policy "owner_update_watch_photos" on public.watch_photos for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id and exists
  (select 1 from public.watches w where w.id = watch_id and w.user_id = (select auth.uid())));
create policy "owner_delete_watch_photos" on public.watch_photos for delete to authenticated
using ((select auth.uid()) = user_id);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('watch-photos', 'watch-photos', false, 15728640,
  array['image/jpeg','image/png','image/webp','image/heic','image/heif'])
on conflict (id) do update set public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy "owner_select_watch_photo_objects" on storage.objects for select to authenticated
using (bucket_id = 'watch-photos' and (storage.foldername(name))[1] = (select auth.uid())::text);
create policy "owner_insert_watch_photo_objects" on storage.objects for insert to authenticated
with check (bucket_id = 'watch-photos' and (storage.foldername(name))[1] = (select auth.uid())::text);
create policy "owner_update_watch_photo_objects" on storage.objects for update to authenticated
using (bucket_id = 'watch-photos' and (storage.foldername(name))[1] = (select auth.uid())::text)
with check (bucket_id = 'watch-photos' and (storage.foldername(name))[1] = (select auth.uid())::text);
create policy "owner_delete_watch_photo_objects" on storage.objects for delete to authenticated
using (bucket_id = 'watch-photos' and (storage.foldername(name))[1] = (select auth.uid())::text);

insert into public.brands (user_id, name)
select distinct user_id, brand from public.watches
where brand is not null and btrim(brand) <> ''
on conflict (user_id, name) do nothing;
