-- Complete the Horoteca catalog with marketplace specifics and field-level claims.
-- No watch data is inserted or modified by this migration.

alter table public.watches
  add column if not exists watch_type text,
  add column if not exists display_type text,
  add column if not exists intended_audience text,
  add column if not exists bezel_type text,
  add column if not exists bezel_material text,
  add column if not exists bezel_color text,
  add column if not exists strap_color text,
  add column if not exists has_original_box boolean,
  add column if not exists has_original_papers boolean,
  add column if not exists included_accessories text[],
  add column if not exists is_customized boolean,
  add column if not exists customization_description text,
  add column if not exists features text[];

alter table public.acquisitions
  add column if not exists estimated_delivery_date date,
  add column if not exists source_document_name text;

alter table public.acquisition_items
  add column if not exists listing_title text,
  add column if not exists listing_url text,
  add column if not exists listing_category text,
  add column if not exists seller_condition_label text,
  add column if not exists seller_condition_description text,
  add column if not exists listing_quantity integer,
  add column if not exists listing_language text,
  add column if not exists listing_specifics jsonb not null default '{}'::jsonb,
  add column if not exists listing_captured_at date;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'acquisition_items_listing_quantity_check'
      and conrelid = 'public.acquisition_items'::regclass
  ) then
    alter table public.acquisition_items
      add constraint acquisition_items_listing_quantity_check
      check (listing_quantity is null or listing_quantity > 0);
  end if;
end $$;

alter table public.movement_calibers
  add column if not exists frequency_vph integer,
  add column if not exists power_reserve_hours numeric(6,2),
  add column if not exists movement_diameter_mm numeric(6,2),
  add column if not exists movement_thickness_mm numeric(6,2),
  add column if not exists has_manual_winding boolean,
  add column if not exists has_hacking_seconds boolean,
  add column if not exists quickset_features text[],
  add column if not exists shock_protection text,
  add column if not exists escapement_type text,
  add column if not exists winding_description text;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'movement_calibers_specs_check'
      and conrelid = 'public.movement_calibers'::regclass
  ) then
    alter table public.movement_calibers
      add constraint movement_calibers_specs_check check (
        (frequency_vph is null or frequency_vph > 0)
        and (power_reserve_hours is null or power_reserve_hours > 0)
        and (movement_diameter_mm is null or movement_diameter_mm > 0)
        and (movement_thickness_mm is null or movement_thickness_mm > 0)
      );
  end if;
end $$;

create table if not exists public.watch_claims (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid()
    references auth.users(id) on delete cascade,
  watch_id bigint not null
    references public.watches(id) on delete cascade,
  source_id bigint
    references public.watch_sources(id) on delete set null,
  field_name text not null,
  asserted_value text not null,
  normalized_value text,
  evidence_classification text not null,
  verification_status text not null default 'pending',
  confidence_percent smallint,
  claim_context text,
  notes text,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint watch_claims_field_name_check check (btrim(field_name) <> ''),
  constraint watch_claims_asserted_value_check check (btrim(asserted_value) <> ''),
  constraint watch_claims_classification_check check (
    evidence_classification in (
      'document_confirmed', 'seller_statement', 'visual_observation',
      'researched', 'estimated', 'missing', 'inconsistent'
    )
  ),
  constraint watch_claims_status_check check (
    verification_status in ('pending', 'accepted', 'rejected', 'superseded')
  ),
  constraint watch_claims_confidence_check check (
    confidence_percent is null or confidence_percent between 0 and 100
  )
);

create index if not exists watch_claims_user_id_idx
  on public.watch_claims (user_id);
create index if not exists watch_claims_watch_id_idx
  on public.watch_claims (watch_id);
create index if not exists watch_claims_source_id_idx
  on public.watch_claims (source_id);
create index if not exists watch_claims_review_idx
  on public.watch_claims (watch_id, verification_status, field_name);
create index if not exists acquisition_items_listing_specifics_gin_idx
  on public.acquisition_items using gin (listing_specifics);

drop trigger if exists watch_claims_set_updated_at on public.watch_claims;
create trigger watch_claims_set_updated_at
before update on public.watch_claims
for each row execute function public.set_updated_at();

alter table public.watch_claims enable row level security;

drop policy if exists owner_select on public.watch_claims;
create policy owner_select on public.watch_claims
for select to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists owner_insert on public.watch_claims;
create policy owner_insert on public.watch_claims
for insert to authenticated
with check (
  (select auth.uid()) = user_id
  and exists (
    select 1 from public.watches watch
    where watch.id = watch_id
      and watch.user_id = (select auth.uid())
  )
  and (
    source_id is null
    or exists (
      select 1 from public.watch_sources source
      where source.id = source_id
        and source.user_id = (select auth.uid())
    )
  )
);

drop policy if exists owner_update on public.watch_claims;
create policy owner_update on public.watch_claims
for update to authenticated
using ((select auth.uid()) = user_id)
with check (
  (select auth.uid()) = user_id
  and exists (
    select 1 from public.watches watch
    where watch.id = watch_id
      and watch.user_id = (select auth.uid())
  )
  and (
    source_id is null
    or exists (
      select 1 from public.watch_sources source
      where source.id = source_id
        and source.user_id = (select auth.uid())
    )
  )
);

drop policy if exists owner_delete on public.watch_claims;
create policy owner_delete on public.watch_claims
for delete to authenticated
using ((select auth.uid()) = user_id);

revoke all privileges on public.watch_claims from anon, authenticated;
grant select, insert, update, delete on public.watch_claims to authenticated;
revoke all privileges on sequence public.watch_claims_id_seq from anon;
grant usage, select on sequence public.watch_claims_id_seq to authenticated;

comment on column public.acquisition_items.listing_specifics is
  'Exact marketplace key/value specifics not promoted to canonical columns.';
comment on table public.watch_claims is
  'Field-level assertions preserved separately from canonical confirmed facts.';
